/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ForAiRouteImport } from './routes/for-ai'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiLinkRouteImport } from './routes/api/link'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CollectionsThemesRouteImport } from './routes/collections.themes'
import { Route as CollectionsCategoryCategoryIdRouteImport } from './routes/collections.category.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiRoute = ForAiRouteImport.update({
  id: '/for-ai',
  path: '/for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkRoute = ApiLinkRouteImport.update({
  id: '/api/link',
  path: '/api/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsThemesRoute = CollectionsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsCategoryCategoryIdRoute =
  CollectionsCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => CollectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/for-ai': typeof ForAiRoute
  '/settings': typeof SettingsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/collections/': typeof CollectionsIndexRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/for-ai': typeof ForAiRoute
  '/settings': typeof SettingsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/for-ai': typeof ForAiRoute
  '/settings': typeof SettingsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/collections/': typeof CollectionsIndexRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/collections'
    | '/for-ai'
    | '/settings'
    | '/api/link'
    | '/api/mcp'
    | '/collections/$id'
    | '/collections/themes'
    | '/collections/'
    | '/collections/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/for-ai'
    | '/settings'
    | '/api/link'
    | '/api/mcp'
    | '/collections/$id'
    | '/collections/themes'
    | '/collections'
    | '/collections/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/collections'
    | '/for-ai'
    | '/settings'
    | '/api/link'
    | '/api/mcp'
    | '/collections/$id'
    | '/collections/themes'
    | '/collections/'
    | '/collections/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ForAiRoute: typeof ForAiRoute
  SettingsRoute: typeof SettingsRoute
  ApiLinkRoute: typeof ApiLinkRoute
  ApiMcpRoute: typeof ApiMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai': {
      id: '/for-ai'
      path: '/for-ai'
      fullPath: '/for-ai'
      preLoaderRoute: typeof ForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link': {
      id: '/api/link'
      path: '/api/link'
      fullPath: '/api/link'
      preLoaderRoute: typeof ApiLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/themes': {
      id: '/collections/themes'
      path: '/themes'
      fullPath: '/collections/themes'
      preLoaderRoute: typeof CollectionsThemesRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/category/$categoryId': {
      id: '/collections/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/collections/category/$categoryId'
      preLoaderRoute: typeof CollectionsCategoryCategoryIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
  CollectionsThemesRoute: typeof CollectionsThemesRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsCategoryCategoryIdRoute: typeof CollectionsCategoryCategoryIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
  CollectionsThemesRoute: CollectionsThemesRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsCategoryCategoryIdRoute: CollectionsCategoryCategoryIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ForAiRoute: ForAiRoute,
  SettingsRoute: SettingsRoute,
  ApiLinkRoute: ApiLinkRoute,
  ApiMcpRoute: ApiMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
