/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ForAiRouteImport } from './routes/for-ai'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiCollectionsRouteImport } from './routes/api/collections'
import { Route as ApiLinkRouteImport } from './routes/api/link'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPlansRouteImport } from './routes/api/plans'
import { Route as CIdRouteImport } from './routes/c.$id'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsIdRouteImport } from './routes/collections.$id'
import { Route as CollectionsThemesRouteImport } from './routes/collections.themes'
import { Route as GIdRouteImport } from './routes/g.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileBadgesRouteImport } from './routes/profile.badges'
import { Route as ProfileBibleRouteImport } from './routes/profile.bible'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileLanguageRouteImport } from './routes/profile.language'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileThemeRouteImport } from './routes/profile.theme'
import { Route as ReadingIndexRouteImport } from './routes/reading.index'
import { Route as ReadingIdRouteImport } from './routes/reading.$id'
import { Route as ReadingAllRouteImport } from './routes/reading.all'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CollectionsCategoryCategoryIdRouteImport } from './routes/collections.category.$categoryId'
import { Route as ReadingCategoryCategoryIdRouteImport } from './routes/reading.category.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAiRoute = ForAiRouteImport.update({
  id: '/for-ai',
  path: '/for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionsRoute = ApiCollectionsRouteImport.update({
  id: '/api/collections',
  path: '/api/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkRoute = ApiLinkRouteImport.update({
  id: '/api/link',
  path: '/api/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsThemesRoute = CollectionsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => CollectionsRoute,
} as any)
const GIdRoute = GIdRouteImport.update({
  id: '/g/$id',
  path: '/g/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBadgesRoute = ProfileBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBibleRoute = ProfileBibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLanguageRoute = ProfileLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileThemeRoute = ProfileThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ProfileRoute,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadingRoute,
} as any)
const ReadingIdRoute = ReadingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReadingRoute,
} as any)
const ReadingAllRoute = ReadingAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ReadingRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryCategoryIdRoute =
  CollectionsCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => CollectionsRoute,
  } as any)
const ReadingCategoryCategoryIdRoute =
  ReadingCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => ReadingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/for-ai': typeof ForAiRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reading': typeof ReadingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/api/collections': typeof ApiCollectionsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/plans': typeof ApiPlansRoute
  '/c/$id': typeof CIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/g/$id': typeof GIdRoute
  '/profile/badges': typeof ProfileBadgesRoute
  '/profile/bible': typeof ProfileBibleRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reading/$id': typeof ReadingIdRoute
  '/reading/all': typeof ReadingAllRoute
  '/u/$handle': typeof UHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
  '/reading/category/$categoryId': typeof ReadingCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/for-ai': typeof ForAiRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/collections': typeof ApiCollectionsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/plans': typeof ApiPlansRoute
  '/c/$id': typeof CIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/g/$id': typeof GIdRoute
  '/profile/badges': typeof ProfileBadgesRoute
  '/profile/bible': typeof ProfileBibleRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reading/$id': typeof ReadingIdRoute
  '/reading/all': typeof ReadingAllRoute
  '/u/$handle': typeof UHandleRoute
  '/collections': typeof CollectionsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reading': typeof ReadingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
  '/reading/category/$categoryId': typeof ReadingCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/for-ai': typeof ForAiRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reading': typeof ReadingRouteWithChildren
  '/settings': typeof SettingsRoute
  '/api/collections': typeof ApiCollectionsRoute
  '/api/link': typeof ApiLinkRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/plans': typeof ApiPlansRoute
  '/c/$id': typeof CIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/collections/themes': typeof CollectionsThemesRoute
  '/g/$id': typeof GIdRoute
  '/profile/badges': typeof ProfileBadgesRoute
  '/profile/bible': typeof ProfileBibleRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reading/$id': typeof ReadingIdRoute
  '/reading/all': typeof ReadingAllRoute
  '/u/$handle': typeof UHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reading/': typeof ReadingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/collections/category/$categoryId': typeof CollectionsCategoryCategoryIdRoute
  '/reading/category/$categoryId': typeof ReadingCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/collections'
    | '/for-ai'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/reading'
    | '/settings'
    | '/api/collections'
    | '/api/link'
    | '/api/mcp'
    | '/api/plans'
    | '/c/$id'
    | '/collections/$id'
    | '/collections/themes'
    | '/g/$id'
    | '/profile/badges'
    | '/profile/bible'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/theme'
    | '/reading/$id'
    | '/reading/all'
    | '/u/$handle'
    | '/collections/'
    | '/profile/'
    | '/reading/'
    | '/api/auth/$'
    | '/collections/category/$categoryId'
    | '/reading/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/for-ai'
    | '/inbox'
    | '/login'
    | '/settings'
    | '/api/collections'
    | '/api/link'
    | '/api/mcp'
    | '/api/plans'
    | '/c/$id'
    | '/collections/$id'
    | '/collections/themes'
    | '/g/$id'
    | '/profile/badges'
    | '/profile/bible'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/theme'
    | '/reading/$id'
    | '/reading/all'
    | '/u/$handle'
    | '/collections'
    | '/profile'
    | '/reading'
    | '/api/auth/$'
    | '/collections/category/$categoryId'
    | '/reading/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/collections'
    | '/for-ai'
    | '/inbox'
    | '/login'
    | '/profile'
    | '/reading'
    | '/settings'
    | '/api/collections'
    | '/api/link'
    | '/api/mcp'
    | '/api/plans'
    | '/c/$id'
    | '/collections/$id'
    | '/collections/themes'
    | '/g/$id'
    | '/profile/badges'
    | '/profile/bible'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications'
    | '/profile/theme'
    | '/reading/$id'
    | '/reading/all'
    | '/u/$handle'
    | '/collections/'
    | '/profile/'
    | '/reading/'
    | '/api/auth/$'
    | '/collections/category/$categoryId'
    | '/reading/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ForAiRoute: typeof ForAiRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReadingRoute: typeof ReadingRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ApiCollectionsRoute: typeof ApiCollectionsRoute
  ApiLinkRoute: typeof ApiLinkRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPlansRoute: typeof ApiPlansRoute
  CIdRoute: typeof CIdRoute
  GIdRoute: typeof GIdRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-ai': {
      id: '/for-ai'
      path: '/for-ai'
      fullPath: '/for-ai'
      preLoaderRoute: typeof ForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collections': {
      id: '/api/collections'
      path: '/api/collections'
      fullPath: '/api/collections'
      preLoaderRoute: typeof ApiCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link': {
      id: '/api/link'
      path: '/api/link'
      fullPath: '/api/link'
      preLoaderRoute: typeof ApiLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/themes': {
      id: '/collections/themes'
      path: '/themes'
      fullPath: '/collections/themes'
      preLoaderRoute: typeof CollectionsThemesRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/g/$id': {
      id: '/g/$id'
      path: '/g/$id'
      fullPath: '/g/$id'
      preLoaderRoute: typeof GIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/badges': {
      id: '/profile/badges'
      path: '/badges'
      fullPath: '/profile/badges'
      preLoaderRoute: typeof ProfileBadgesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/bible': {
      id: '/profile/bible'
      path: '/bible'
      fullPath: '/profile/bible'
      preLoaderRoute: typeof ProfileBibleRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/language': {
      id: '/profile/language'
      path: '/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof ProfileLanguageRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/theme': {
      id: '/profile/theme'
      path: '/theme'
      fullPath: '/profile/theme'
      preLoaderRoute: typeof ProfileThemeRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/reading/': {
      id: '/reading/'
      path: '/'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof ReadingRoute
    }
    '/reading/$id': {
      id: '/reading/$id'
      path: '/$id'
      fullPath: '/reading/$id'
      preLoaderRoute: typeof ReadingIdRouteImport
      parentRoute: typeof ReadingRoute
    }
    '/reading/all': {
      id: '/reading/all'
      path: '/all'
      fullPath: '/reading/all'
      preLoaderRoute: typeof ReadingAllRouteImport
      parentRoute: typeof ReadingRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/category/$categoryId': {
      id: '/collections/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/collections/category/$categoryId'
      preLoaderRoute: typeof CollectionsCategoryCategoryIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/reading/category/$categoryId': {
      id: '/reading/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/reading/category/$categoryId'
      preLoaderRoute: typeof ReadingCategoryCategoryIdRouteImport
      parentRoute: typeof ReadingRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIdRoute: typeof CollectionsIdRoute
  CollectionsThemesRoute: typeof CollectionsThemesRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsCategoryCategoryIdRoute: typeof CollectionsCategoryCategoryIdRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIdRoute: CollectionsIdRoute,
  CollectionsThemesRoute: CollectionsThemesRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsCategoryCategoryIdRoute: CollectionsCategoryCategoryIdRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileBadgesRoute: typeof ProfileBadgesRoute
  ProfileBibleRoute: typeof ProfileBibleRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileLanguageRoute: typeof ProfileLanguageRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileThemeRoute: typeof ProfileThemeRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBadgesRoute: ProfileBadgesRoute,
  ProfileBibleRoute: ProfileBibleRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileLanguageRoute: ProfileLanguageRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileThemeRoute: ProfileThemeRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ReadingRouteChildren {
  ReadingIdRoute: typeof ReadingIdRoute
  ReadingAllRoute: typeof ReadingAllRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
  ReadingCategoryCategoryIdRoute: typeof ReadingCategoryCategoryIdRoute
}

const ReadingRouteChildren: ReadingRouteChildren = {
  ReadingIdRoute: ReadingIdRoute,
  ReadingAllRoute: ReadingAllRoute,
  ReadingIndexRoute: ReadingIndexRoute,
  ReadingCategoryCategoryIdRoute: ReadingCategoryCategoryIdRoute,
}

const ReadingRouteWithChildren =
  ReadingRoute._addFileChildren(ReadingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ForAiRoute: ForAiRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReadingRoute: ReadingRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ApiCollectionsRoute: ApiCollectionsRoute,
  ApiLinkRoute: ApiLinkRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPlansRoute: ApiPlansRoute,
  CIdRoute: CIdRoute,
  GIdRoute: GIdRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
